# Generated 2024-05-05 from:
# /home/batch3/Math/speechbrain/recipes/VoxCeleb/SpeakerRec/hparams/train_ecapa_tdnn.yaml
# yamllint disable
# ################################
# Model: Speaker identification with ECAPA
# Authors: Hwidong Na & Mirco Ravanelli
# ################################

# Basic parameters
seed: 1986
__set_seed: !apply:torch.manual_seed [1986]
output_folder: results/ecapa_augment/1986
save_folder: results/ecapa_augment/1986/save
train_log: results/ecapa_augment/1986/train_log.txt

# Data for augmentation
NOISE_DATASET_URL: 
  https://www.dropbox.com/scl/fi/a09pj97s5ifan81dqhi4n/noises.zip?rlkey=j8b0n9kdjdr32o1f06t0cw5b7&dl=1
RIR_DATASET_URL: 
  https://www.dropbox.com/scl/fi/linhy77c36mu10965a836/RIRs.zip?rlkey=pg9cu8vrpn2u173vhiqyu743u&dl=1

# Data files
data_folder: /home/batch3/Math/Voxceleb1
                           # e.g. /path/to/Voxceleb
data_folder_noise: /home/batch3/Math/Voxceleb1/noise # The noisy sequences for data augmentation will automatically be downloaded here.
data_folder_rir: /home/batch3/Math/Voxceleb1/rir # The impulse responses used for data augmentation will automatically be downloaded here.
train_annotation: results/ecapa_augment/1986/save/train.csv
valid_annotation: results/ecapa_augment/1986/save/dev.csv
noise_annotation: results/ecapa_augment/1986/save/noise.csv
rir_annotation: results/ecapa_augment/1986/save/rir.csv

# Use the following links for the official voxceleb splits:
# VoxCeleb1 (cleaned): https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt
# VoxCeleb1-H (cleaned): https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/list_test_hard2.txt
# VoxCeleb1-E (cleaned): https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/list_test_all2.txt.
# VoxCeleb1-E and VoxCeleb1-H lists are drawn from the VoxCeleb1 training set.
# Therefore you cannot use any files in VoxCeleb1 for training if you are using these lists for testing.
verification_file: https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt

split_ratio: [90, 10]
skip_prep: false
ckpt_interval_minutes: 15 # save checkpoint every N min

# Training parameters
number_of_epochs: 10
batch_size: 32
lr: 0.001
base_lr: 0.00000001
max_lr: 0.001
step_size: 65000
sample_rate: 16000
sentence_len: 3.0 # seconds
shuffle: true
random_chunk: true

# Feature parameters
n_mels: 80
left_frames: 0
right_frames: 0
deltas: false

# Number of speakers
out_n_neurons: 1211 #1211 for vox1  # 5994 for vox2, 7205 for vox1+vox2

num_workers: 4
dataloader_options:
  batch_size: 32
  shuffle: true
  num_workers: 4

# Functions
compute_features: &id005 !new:speechbrain.lobes.features.Fbank
  n_mels: 80
  left_frames: 0
  right_frames: 0
  deltas: false

embedding_model: &id006 !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
  input_size: 80
  channels: [1024, 1024, 1024, 1024, 3072]
  kernel_sizes: [5, 3, 3, 3, 1]
  dilations: [1, 2, 3, 4, 1]
  groups: [1, 1, 1, 1, 1]
  attention_channels: 128
  lin_neurons: 192

classifier: &id007 !new:speechbrain.lobes.models.ECAPA_TDNN.Classifier
  input_size: 192
  out_neurons: 1211

epoch_counter: &id009 !new:speechbrain.utils.epoch_loop.EpochCounter
  limit: 10

############################## Augmentations ###################################

# Download and prepare the dataset of noisy sequences for augmentation
prepare_noise_data: !name:speechbrain.augment.preparation.prepare_dataset_from_URL
  URL: 
    https://www.dropbox.com/scl/fi/a09pj97s5ifan81dqhi4n/noises.zip?rlkey=j8b0n9kdjdr32o1f06t0cw5b7&dl=1
  dest_folder: /home/batch3/Math/Voxceleb1/noise
  ext: wav
  csv_file: results/ecapa_augment/1986/save/noise.csv


# Add noise to input signal
add_noise: &id001 !new:speechbrain.augment.time_domain.AddNoise
  csv_file: results/ecapa_augment/1986/save/noise.csv
  snr_low: 0
  snr_high: 15
  noise_sample_rate: 16000
  clean_sample_rate: 16000
  num_workers: 4

# Download and prepare the dataset of room impulse responses for augmentation
prepare_rir_data: !name:speechbrain.augment.preparation.prepare_dataset_from_URL
  URL: 
    https://www.dropbox.com/scl/fi/linhy77c36mu10965a836/RIRs.zip?rlkey=pg9cu8vrpn2u173vhiqyu743u&dl=1
  dest_folder: /home/batch3/Math/Voxceleb1/rir
  ext: wav
  csv_file: results/ecapa_augment/1986/save/rir.csv

# Add reverberation to input signal
add_reverb: &id002 !new:speechbrain.augment.time_domain.AddReverb
  csv_file: results/ecapa_augment/1986/save/rir.csv
  reverb_sample_rate: 16000
  clean_sample_rate: 16000
  num_workers: 4

# Frequency drop: randomly drops a number of frequency bands to zero.
drop_freq: &id003 !new:speechbrain.augment.time_domain.DropFreq
  drop_freq_low: 0
  drop_freq_high: 1
  drop_freq_count_low: 1
  drop_freq_count_high: 3
  drop_freq_width: 0.05

# Time drop: randomly drops a number of temporal chunks.
drop_chunk: &id004 !new:speechbrain.augment.time_domain.DropChunk
  drop_length_low: 1000
  drop_length_high: 2000
  drop_count_low: 1
  drop_count_high: 5

# Augmenter: Combines previously defined augmentations to perform data augmentation
wav_augment: !new:speechbrain.augment.augmenter.Augmenter
  parallel_augment: true
  concat_original: true
  min_augmentations: 4
  max_augmentations: 4
  augment_prob: 1.0
  augmentations: [*id001, *id002, *id003, *id004]

mean_var_norm: &id008 !new:speechbrain.processing.features.InputNormalization

  norm_type: sentence
  std_norm: false

modules:
  compute_features: *id005
  embedding_model: *id006
  classifier: *id007
  mean_var_norm: *id008
compute_cost: !new:speechbrain.nnet.losses.LogSoftmaxWrapper
  loss_fn: !new:speechbrain.nnet.losses.AdditiveAngularMargin
    margin: 0.2
    scale: 30

# compute_error: !name:speechbrain.nnet.losses.classification_error

opt_class: !name:torch.optim.Adam
  lr: 0.001
  weight_decay: 0.000002

lr_annealing: &id010 !new:speechbrain.nnet.schedulers.CyclicLRScheduler
  base_lr: 0.00000001
  max_lr: 0.001
  step_size: 65000

# Logging + checkpoints
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: results/ecapa_augment/1986/train_log.txt

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
  metric: !name:speechbrain.nnet.losses.classification_error
    reduction: batch

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: results/ecapa_augment/1986/save
  recoverables:
    embedding_model: *id006
    classifier: *id007
    normalizer: *id008
    counter: *id009
    lr_annealing: *id010
